# config context path to "/" by setting an empty string
server:
  port: 8080

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost/test1
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.springframework:
      security: DEBUG

springfox:
  documentation:
    swagger:
      v2:
      path: ${management.context-path}/api-docs
